name: Mac Release
run-name: ${{ github.actor }} is building a Mac release

on:
  push:
    branches: ["latest"]

  workflow_dispatch:

permissions:
  contents: write 

jobs:
  deploy-on-mac:
    runs-on: macos-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: brainsatplay
          environment-file: environment.yml
          auto-activate-base: false
          
      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.APPLE_CERTIFICATE }}
          p12-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}

      - name: Build and deploy on Mac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
        run: npm run build -- --target desktop --publish
